services:
  len_analyzer:
    image: len_analyzer:dev
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: len_analyzer
    ports:
      - "5055:5055/tcp"

networks:
  lighthouse_server:
